# This is a basic workflow to help you get started with Actions

name: CI retry test

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  fail-fast:
    runs-on: ubuntu-latest
    steps:
      - name: Always fail
        run: |
          echo "This job will fail on purpose"
          exit 1

  long-sleeper:
    runs-on: ubuntu-latest
    steps:
      - name: Sleep for a long time
        run: |
          echo "Sleeping for 5 minutes..."
          sleep 300

